// Auto-generated by test_coverage. Do not edit by hand.
// Consider adding this file to your .gitignore.

import 'authentication_test.dart' as authentication_test;
import 'collection_test.dart' as collection_test;
import 'document_test.dart' as document_test;
import 'index_test.dart' as index_test;
import 'kuzzle_dart_test.dart' as kuzzle_dart_test;
import 'memory_storage_test.dart' as memory_storage_test;

void main() {
  index_test.main();
  collection_test.main();
  authentication_test.main();
  document_test.main();
  memory_storage_test.main();
  kuzzle_dart_test.main();
}
