// Auto-generated by test_coverage. Do not edit by hand.
// Consider adding this file to your .gitignore.

import 'authentication_test.dart' as authentication_test;
import 'index_test.dart' as index_test;
import 'server_test.dart' as server_test;

void main() {
  index_test.main();
  authentication_test.main();
  server_test.main();
}
